### ISSUE TITLE
spliddit.org down?

### ISSUE THREAD

**Issue by gchan** [jogo279/spliddit#3]
Hi there, 

I noticed the site is currently unavailable.

Is anyone aware of this and will it be brought back online?

I've used spliddit a couple of time in the past to split Airbnbs and would love to use it again.

Thanks,
Gordon

cc @nisarg89 @jogo279

**Comment by nisarg89** [comment]
Hi Gordon,

Yes, we're aware of this. The site is down due to technical issues related to infrastructural changes in the cloud service we are using. We're working to bring it back online but it's hard to tell when that might happen. Sorry for the inconvenience!

Best,
Nisarg

**Comment by jajanet** [comment]
Should this issue be reopened so it's easier for random people to understand that this is being looked into?

Also is there anything potential contributors can do to help get it back up, or at least some of the functionality?

I'm particularly interested in writing something for the rent splitting application part of this. It would take in the input (array of arrays, n room splits for n roommates), then return the room assignments and costs accordingly with some input validation. Basically the barebones algorithm without any of the web/database code

I've been attempting this with limited knowledge of Rails, and it seems like the function input/output call is [here](https://github.com/nisarg89/spliddit/blob/master/app/views/javascripts/demos/rent.js.erb#L276-L277), but I don't know what `../../../demo/create` is and the file finder isn't helpful here

This may be a helpful stop gap to allow people to use some functionality of this

**Comment by nisarg89** [comment]
Yes, good idea. I'm reopening the issue. As an update, we've been working on this more intensely over the summer with good progress, so we should be able to deploy in a couple of months or so. 

For your needs, you can look at the following code in app/models//splitting_rent_instance.rb: https://github.com/nisarg89/spliddit/blob/42732c9e198a5d24cdd0c3e2ca0673b05e3f24de/app/models/splitting_rent_instance.rb#L10-L39

It writes a text file containing data from a rent division instance and calls the Java code in bin/rent.jar to solve the instance. I believe this should suffice for your purpose.

**Comment by jajanet** [comment]
Thanks a ton for the info! I wrote something out but am having trouble with what the final format of the generated file to feed into the executable should look like from that code snippet. I think it should look something like this but doesn't seem right:
```
(ROOM/HOUSEMATECOUNT)
(RENT COST)
(HOUSEMATE1) (ROOM1) (ROOM1HOUSEMATE1COST divided by ROOMCOUNT)
...
(HOUSEMATE1) (ROOMN) (ROOMNHOUSEMATE1COST divided by ROOMCOUNT)
...
(HOUSEMATEN) (ROOMN) (ROOMNHOUSEMATENCOST divided by ROOMCOUNT)
```

Could you provide an example of the final output with the original example given (like below but the bids like the following)? It would be super helpful and I think I can get it working with that info after
```
var housemates = ["Alice", "Bob", "Claire"];
var rooms = ["Master Bedroom", "Basement", "2nd Floor"];
var rent = 1000;

# imagine bids like this
var bids = {"Alice": {"Master Bedroom": 400, "Basement": 300, "2nd Floor": 300},
        "Bob": {"Master Bedroom": 350, "Basement": 325, "2nd Floor": 325},
        "Claire": {"Master Bedroom": 380, "Basement": 305, "2nd Floor": 315}};
```

If this data was following the format given above, it would look something like (which I think I'm not understanding correctly)
```
4
1000
Alice MasterBedroom 116.67
...
Alice 2ndFloor 100
...
Claire 2ndFloor 105
```

**Comment by nisarg89** [comment]
Here's the file that's created in my development environment when I simulate your instance.

3
1000
81 81_0 400.0
81 82_0 300.0
81 83_0 300.0
82 81_0 350.0
82 82_0 325.0
82 83_0 325.0
83 81_0 380.0
83 82_0 305.0
83 83_0 315.0 

The numbers in the first two columns don't really matter. They are just identifiers created to represent roommates and rooms. I think the only problem with your format above was that it started with 4, when the number of roommates/rooms is 3 in your example.

**Comment by nemoyatpeace** [comment]
Hoping you are able to get this running again sometime soon.  I use it in my classroom each year, was sad to see that it is down this year, and I can't find any alternatives.

**Comment by nisarg89** [comment]
Just adding a note that Spliddit.org has been live again since the summer of 2024.
