### ISSUE TITLE
Spliddit is down

### ISSUE THREAD

**Issue by mlhetland** [jogo279/spliddit#4]
It seems [Spliddit](http://www.spliddit.org) is down? Maybe caused by some of the recent changes, here (given that the two events seem to coincide, more or less)?

**Comment by mlhetland** [comment]
Ah. I see this has been addressed in https://github.com/jogo279/spliddit/issues/3. Sorry for the duplicate.

**Comment by nisarg89** [comment]
Hi Magnus,

Yes, unfortunately we haven't been able to restore it yet. But we're working on it!
